# Generated by Django 4.2.4 on 2023-09-10 21:03

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("document", "0001_initial"),
        ("company", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("email", models.CharField(max_length=255)),
                (
                    "password_reseted_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("verified_email", models.BooleanField(default=False)),
                ("password", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="company.company",
                    ),
                ),
                ("documents", models.ManyToManyField(to="document.document")),
            ],
        ),
    ]
