# Generated by Django 4.2.4 on 2023-09-10 21:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="password",
            field=models.CharField(
                max_length=255,
                validators=[django.core.validators.MinLengthValidator(6)],
            ),
        ),
    ]
