# Generated by Django 4.2.4 on 2023-09-10 21:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("company", "0003_alter_company_created_by"),
        ("user", "0003_alter_user_company"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="id",
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="user",
            name="company",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user",
                to="company.company",
            ),
        ),
    ]
