# Generated by Django 4.2.4 on 2023-09-10 21:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("company", "0003_alter_company_created_by"),
        ("user", "0004_user_id_alter_user_company"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="company",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user",
                to="company.company",
            ),
        ),
    ]
