# Generated by Django 4.2.4 on 2023-09-10 21:03

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("timezone", models.CharField(default="-03:00", max_length=50)),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("pt", "Português"),
                            ("en", "English"),
                            ("es", "Español"),
                        ],
                        default="pt",
                        max_length=2,
                    ),
                ),
            ],
        ),
    ]
