# Generated by Django 4.2.4 on 2023-09-10 21:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("user", "0001_initial"),
        ("company", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="created_companies",
                to="user.user",
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="users",
            field=models.ManyToManyField(related_name="companies", to="user.user"),
        ),
    ]
