# Generated by Django 4.2.4 on 2023-09-10 21:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0002_alter_user_password"),
        ("company", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="created_company",
                to="user.user",
            ),
        ),
    ]
