# Generated by Django 4.2.4 on 2023-09-10 21:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0006_alter_user_id"),
        ("company", "0003_alter_company_created_by"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="created_by",
            field=models.ForeignKey(
                db_constraint=False,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="created_company",
                to="user.user",
            ),
        ),
    ]
